// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {config} from '../models';

export function GetAppState():Promise<config.AppState>;

export function OpenDirectory(arg1:string):Promise<void>;

export function OpenPowerShellAdmin(arg1:string):Promise<void>;

export function OpenWithCustomTool(arg1:string,arg2:string):Promise<void>;

export function ResolvePath(arg1:string):Promise<string>;

export function SaveAppState(arg1:config.AppState):Promise<void>;

export function ValidatePath(arg1:string):Promise<boolean>;
