// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {config} from '../models';
import {terminal} from '../models';
import {attachment} from '../models';

export function GetAppState():Promise<config.AppState>;

export function GetTerminalSessions():Promise<Array<terminal.SessionInfo>>;

export function OpenAttachment(arg1:string):Promise<void>;

export function OpenDirectory(arg1:string):Promise<void>;

export function OpenPowerShellAdmin(arg1:string):Promise<void>;

export function OpenWithCustomTool(arg1:string,arg2:string):Promise<void>;

export function ResizeTerminal(arg1:string,arg2:number,arg3:number):Promise<void>;

export function ResolvePath(arg1:string):Promise<string>;

export function SaveAppState(arg1:config.AppState):Promise<void>;

export function SaveAttachment(arg1:attachment.SaveRequest):Promise<attachment.FileInfo>;

export function StartEmbeddedTerminal(arg1:string):Promise<terminal.SessionInfo>;

export function StopTerminal(arg1:string):Promise<void>;

export function ValidatePath(arg1:string):Promise<boolean>;

export function WriteTerminalInput(arg1:string,arg2:string):Promise<void>;
