// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function GetAppState() {
  return window['go']['main']['App']['GetAppState']();
}

export function OpenDirectory(arg1) {
  return window['go']['main']['App']['OpenDirectory'](arg1);
}

export function OpenPowerShellAdmin(arg1) {
  return window['go']['main']['App']['OpenPowerShellAdmin'](arg1);
}

export function OpenWithCustomTool(arg1, arg2) {
  return window['go']['main']['App']['OpenWithCustomTool'](arg1, arg2);
}

export function ResolvePath(arg1) {
  return window['go']['main']['App']['ResolvePath'](arg1);
}

export function SaveAppState(arg1) {
  return window['go']['main']['App']['SaveAppState'](arg1);
}

export function ValidatePath(arg1) {
  return window['go']['main']['App']['ValidatePath'](arg1);
}
